# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Гарипов Тимур Исмагилевич

Группа: 317

In [3]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [66]:
arr = [i for i in range(7, 101, 7) if (i % 5 != 0)]
arr

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [67]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [68]:
def sort_tokens(s):
    return ','.join(sorted(s.split(',')))


In [69]:
print(sort_tokens(u'ночь,фонарь,улица'))

ночь,улица,фонарь


In [70]:
print(sort_tokens(u'баа,аа,аба,бб,а,б,ааа,ва,ав'))

а,аа,ааа,аба,ав,б,баа,бб,ва


In [71]:
print(sort_tokens(u'qwer,qw,qwee,q,qwerty'))

q,qw,qwee,qwer,qwerty


#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [72]:
def remove_duplicates(a):
    return sorted(list(set(a)))

In [76]:
print(remove_duplicates(['cc', 'aba', 'bb', 'aba', 'ba', 'ba', 'bb', 'ba', 'ab', 'a']))

['a', 'ab', 'aba', 'ba', 'bb', 'cc']


#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [3]:
map(lambda x: x.lower(), ["abCDefg", "HIjkL"])

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [4]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [94]:
from collections import defaultdict
d = defaultdict(int)
print d
d['abc'] += 1
print d
d['xxx']
print d

defaultdict(<type 'int'>, {})
defaultdict(<type 'int'>, {'abc': 1})
defaultdict(<type 'int'>, {'xxx': 0, 'abc': 1})


In [97]:
def word_counts(texts):
    res = reduce(lambda x, y: x + y, map(lambda x: x.split(), texts))
    d = defaultdict(int)
    for s in res:
        d[s] += 1
    for s in d:
        print s, d[s]

In [98]:
word_counts(['aaa aa a b c def', 'aa  aaaa b b c de def'])

aa 2
a 1
c 2
b 3
aaa 1
de 1
aaaa 1
def 2


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [99]:
from urllib import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [100]:
raw_text[1000:1100]

u'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

In [105]:
import re

In [154]:
raw_text = raw_text.lower()
words= re.split('[^a-z]', raw_text)
words = filter(lambda x: len(x) > 0, words)
print(len(words))

d = defaultdict(int)
for w in words:
    d[w] += 1
srt = sorted(d.items(), key = lambda x:x[1], reverse = True)
srt[:20]

211866


[(u'the', 8003),
 (u'and', 7042),
 (u'to', 5497),
 (u'he', 4900),
 (u'a', 4668),
 (u'i', 4405),
 (u'you', 4118),
 (u'of', 3928),
 (u'it', 3463),
 (u'that', 3308),
 (u'in', 3254),
 (u'was', 2827),
 (u'his', 2116),
 (u'at', 2082),
 (u'her', 1829),
 (u'but', 1801),
 (u'not', 1775),
 (u's', 1765),
 (u'with', 1757),
 (u'she', 1695)]

In [157]:
filter(lambda x: x[1] == 1, d.items())[:20]

[(u'fawn', 1),
 (u'writings', 1),
 (u'nunnery', 1),
 (u'fedosya', 1),
 (u'clotted', 1),
 (u'preface', 1),
 (u'cyprus', 1),
 (u'increase', 1),
 (u'wheeled', 1),
 (u'superficially', 1),
 (u'meadows', 1),
 (u'fogeys', 1),
 (u'anaemic', 1),
 (u'straws', 1),
 (u'busybody', 1),
 (u'reliable', 1),
 (u'scraped', 1),
 (u'errors', 1),
 (u'cooking', 1),
 (u'contributed', 1)]

## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [179]:
N = 1000
x = np.empty(N)
for i in range(N):
    a = np.random.normal(size = (10, 10))
    b = np.random.normal(size = (10, 10))
    x[i] = np.max(np.dot(a, b))
print x.mean()
print np.percentile(x, 95)

8.39869449401
11.9235001803


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [191]:
x = np.random.poisson(5, 1000)
b = np.bincount(x)
print(b)

[  5  28  78 140 158 182 159 124  62  35  13   5   7   4]


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [193]:
def my_func(a):
    res = np.array([], dtype='int64')
    for i in range(len(a)):
        res = np.append(res, np.repeat(np.array([i], dtype='int64'), a[i]))
    return res

In [199]:
np.all(my_func(b) == sorted(x))

True

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [239]:
def scale(X):
    D = np.std(X, axis = 0)
    D[np.abs(D) <= 1e-9] = 1.0
    return (X - np.mean(X, axis = 0)) / D
    

In [240]:
X = np.reshape(np.arange(50), (5, 10))
Y = scale(X)
print(np.mean(Y, axis = 0))
print(np.std(Y, axis = 0))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [241]:
X = np.reshape(np.arange(50), (5, 10))
X[:, 1] = 10
print(X)
Y = scale(X)
print(np.mean(Y, axis = 0))
print(np.std(Y, axis = 0))
print(Y)

[[ 0 10  2  3  4  5  6  7  8  9]
 [10 10 12 13 14 15 16 17 18 19]
 [20 10 22 23 24 25 26 27 28 29]
 [30 10 32 33 34 35 36 37 38 39]
 [40 10 42 43 44 45 46 47 48 49]]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  0.  1.  1.  1.  1.  1.  1.  1.  1.]
[[-1.41421356  0.         -1.41421356 -1.41421356 -1.41421356 -1.41421356
  -1.41421356 -1.41421356 -1.41421356 -1.41421356]
 [-0.70710678  0.         -0.70710678 -0.70710678 -0.70710678 -0.70710678
  -0.70710678 -0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.70710678  0.          0.70710678  0.70710678  0.70710678  0.70710678
   0.70710678  0.70710678  0.70710678  0.70710678]
 [ 1.41421356  0.          1.41421356  1.41421356  1.41421356  1.41421356
   1.41421356  1.41421356  1.41421356  1.41421356]]


#### 5. Сгенерируйте матрицу с элементами из норм(ального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [243]:
import scipy.linalg
X = np.random.normal(10, 1, size = (7, 7))
X

array([[ 10.73189442,  10.83628325,   9.39837748,   8.54083326,
         10.13707054,  10.57539006,   9.41664493],
       [  8.95478279,   9.07518735,   9.09474535,   9.5869317 ,
         10.60884626,   8.95898565,   9.84816484],
       [  9.78871221,   9.71945777,  11.43471307,   9.8862956 ,
         10.50780158,   9.82170477,   9.46499793],
       [  9.71897792,   9.44439703,  12.07086386,   9.43431617,
         11.78972068,   8.24899733,  10.39018098],
       [ 10.23728977,  12.05030846,  11.25077488,  10.95500265,
         11.0334591 ,   9.13679794,  10.42261072],
       [ 10.9512506 ,   9.6317293 ,   8.85766118,  10.13718575,
          9.6492129 ,   9.25734786,   9.13944917],
       [  8.73737722,  10.85256206,   9.94546817,  11.90025753,
         11.31526216,   9.22822869,   9.87594901]])

In [245]:
print(scipy.linalg.det(X))

847.820582213034

In [274]:
print(X.trace())

70.8428669796


In [252]:
print(X.min(), X.max())

(8.2489973310369304, 12.070863860157251)


In [264]:
print(np.max(scipy.linalg.eigvals(X.T * X)) ** 0.5)

(26.6896712209+0j)


In [261]:
print(scipy.linalg.norm(X, ord = 'fro'))

70.6032049398


In [265]:
print(scipy.linalg.eigvals(X))

[ 70.35360455+0.j           2.22543138+0.69657984j   2.22543138-0.69657984j
  -0.69202150+1.13937256j  -0.69202150-1.13937256j  -0.64545019+0.j
  -1.93210713+0.j        ]


In [270]:
print(scipy.linalg.inv(X))

[[  5.71513560e-02  -3.36690236e-01  -2.20645780e-01   2.53454953e-01
   -1.41374272e-01   4.42039157e-01  -3.38123914e-02]
 [  2.57585574e-01  -2.80598562e-01  -2.48207635e-01   4.91454570e-03
    2.63219448e-01  -1.63822830e-01   1.40728484e-01]
 [ -1.61914415e-01  -1.11568866e-01   4.07605783e-01  -1.65254423e-02
    1.44694688e-01  -1.04463946e-01  -1.63650085e-01]
 [ -3.17193602e-01  -1.20444449e-02   1.62451776e-01  -1.68921364e-01
    1.11677701e-03   2.17217373e-01   1.34280377e-01]
 [  5.80037038e-01  -7.79738461e-01  -6.30785354e-01   7.85779594e-01
   -8.46463316e-01   4.71135241e-02   8.52044285e-01]
 [  1.19007210e-01   2.21706571e-01   4.10978207e-01  -3.23142198e-01
   -1.83314849e-01  -1.96961253e-01  -1.27295894e-02]
 [ -5.64129387e-01   1.41929911e+00   2.00426978e-01  -6.07797583e-01
    8.29886250e-01  -2.37532984e-01  -9.84802596e-01]]


## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [4]:
data = pd.read_csv('./data/2008.csv.bz2')

In [5]:
data.CancellationCode.value_counts().argmax()

'B'

#### 1. 'B' - weather

In [7]:
print data.Distance.mean(), data.Distance.min(), data.Distance.max()

726.387029425 11 4962


#### 2. среднее: 726.38702942539283, минимальное: 11, максимальное: 4962

In [8]:
f = data[data.Distance == 11]
f[[0, 1, 2, 3, 8, 9]]

Year  Month  DayofMonth  DayOfWeek UniqueCarrier  FlightNum
2547298  2008      5          15          4            OH       4988
4392215  2008      8          10          7            OH       5572

In [9]:
x = data[(data.UniqueCarrier == 'OH') & (data.FlightNum == 4988)]
x[[0, 1, 2, 3, 8, 9, 18]]

Year  Month  DayofMonth  DayOfWeek UniqueCarrier  FlightNum  Distance
151771   2008      1           3          4            OH       4988       834
152430   2008      1           4          5            OH       4988       834
153088   2008      1           5          6            OH       4988       834
153545   2008      1           6          7            OH       4988       834
154096   2008      1           7          1            OH       4988       834
154750   2008      1           8          2            OH       4988       834
155308   2008      1           9          3            OH       4988       834
155962   2008      1          10          4            OH       4988       834
156627   2008      1          11          5            OH       4988       834
157287   2008      1          12          6            OH       4988       834
157747   2008      1          13          7            OH       4988       834
158301   2008      1          14          1            OH       4988       834
158958   2008      1          15          2            OH       4988       834
159514   2008      1          16          3            OH       4988       834
160169   2008      1          17          4            OH       4988       834
160833   2008      1          18          5            OH       4988       834
161492   2008      1          19          6            OH       4988       834
161950   2008      1          20          7            OH       4988       834
162493   2008      1          21          1            OH       4988       834
163151   2008      1          22          2            OH       4988       834
163707   2008      1          23          3            OH       4988       834
164361   2008      1          24          4            OH       4988       834
165027   2008      1          25          5            OH       4988       834
165688   2008      1          26          6            OH       4988       834
166150   2008      1          27          7            OH       4988       834
166704   2008      1          28          1            OH       4988       834
167361   2008      1          29          2            OH       4988       834
167917   2008      1          30          3            OH       4988       834
168567   2008      1          31          4            OH       4988       834
453560   2008      1           1          2            OH       4988       834
...       ...    ...         ...        ...           ...        ...       ...
1950510  2008      4          22          2            OH       4988       834
1951061  2008      4          23          3            OH       4988       834
1951699  2008      4          24          4            OH       4988       834
1952338  2008      4          25          5            OH       4988       834
1952964  2008      4          26          6            OH       4988       834
1953394  2008      4          27          7            OH       4988       834
1953949  2008      4          28          1            OH       4988       834
1954581  2008      4          29          2            OH       4988       834
1955125  2008      4          30          3            OH       4988       834
2237623  2008      4           1          2            OH       4988       834
2238161  2008      4           2          3            OH       4988       834
2238804  2008      4           3          4            OH       4988       834
2239451  2008      4           4          5            OH       4988       834
2540716  2008      5           3          6            OH       4988       834
2541127  2008      5           4          7            OH       4988       834
2541649  2008      5           5          1            OH       4988       834
2542256  2008      5           6          2            OH       4988       834
2542783  2008      5           7          3            OH       4988       834
2543388  2008      5           8          4            OH  

In [10]:
x.Distance.value_counts()

834    130
96       1
11       1
dtype: int64

In [11]:
y = data[(data.UniqueCarrier == 'OH') & (data.FlightNum == 5572)]
y[[0, 1, 2, 3, 8, 9, 18]]

Year  Month  DayofMonth  DayOfWeek UniqueCarrier  FlightNum  Distance
151629   2008      1           2          3            OH       5572       544
152291   2008      1           3          4            OH       5572       544
152949   2008      1           4          5            OH       5572       544
153419   2008      1           5          6            OH       5572       544
153963   2008      1           6          7            OH       5572       544
154611   2008      1           7          1            OH       5572       544
155185   2008      1           8          2            OH       5572       544
155823   2008      1           9          3            OH       5572       544
156485   2008      1          10          4            OH       5572       544
157148   2008      1          11          5            OH       5572       544
157622   2008      1          12          6            OH       5572       544
158169   2008      1          13          7            OH       5572       544
158819   2008      1          14          1            OH       5572       544
159392   2008      1          15          2            OH       5572       544
160029   2008      1          16          3            OH       5572       544
160692   2008      1          17          4            OH       5572       544
161355   2008      1          18          5            OH       5572       544
161828   2008      1          19          6            OH       5572       544
162361   2008      1          20          7            OH       5572       544
163012   2008      1          21          1            OH       5572       544
163585   2008      1          22          2            OH       5572       544
164222   2008      1          23          3            OH       5572       544
164885   2008      1          24          4            OH       5572       544
165549   2008      1          25          5            OH       5572       544
166024   2008      1          26          6            OH       5572       544
166572   2008      1          27          7            OH       5572       544
167222   2008      1          28          1            OH       5572       544
167795   2008      1          29          2            OH       5572       544
168432   2008      1          30          3            OH       5572       544
169083   2008      1          31          4            OH       5572       544
...       ...    ...         ...        ...           ...        ...       ...
4388109  2008      8           3          7            OH       5572       544
4388724  2008      8           4          1            OH       5572       544
4389314  2008      8           5          2            OH       5572       544
4389938  2008      8           6          3            OH       5572       544
4390571  2008      8           7          4            OH       5572       544
4391200  2008      8           8          5            OH       5572       544
4391679  2008      8           9          6            OH       5572       544
4392214  2008      8          10          7            OH       5572       544
4392215  2008      8          10          7            OH       5572        11
4392834  2008      8          11          1            OH       5572       544
4393421  2008      8          12          2            OH       5572       544
4394045  2008      8          13          3            OH       5572       544
4394677  2008      8          14          4            OH       5572       544
4395309  2008      8          15          5            OH       5572       544
4395786  2008      8          16          6            OH       5572       544
4396327  2008      8          17          7            OH       5572       544
4396949  2008      8          18          1            OH       5572       544
4397462  2008      8          19          2            OH       5572       544
4398047  2008      8          20          3            OH  

In [12]:
y.Distance.value_counts()

544    243
11       1
dtype: int64

#### 3. Дистанция кратчайшего полёта дейтсвительно выглядит подозрительно (11 миль). 
#### Рейсы, которые совершили полёт на такую дистаницию, в остальные дни проходили существенно другое расстояние.
#### Видимо дистанция 11 миль появилась в данных в результате ошибки.

In [13]:
data.Origin.value_counts().argmax()

'ATL'

#### 4. Аэропорт William B Hartsfield-Atlanta Intl, город Atlanta

In [14]:
g = data.groupby('Origin')
g.AirTime.mean().argmax()

'SJU'

#### 5. Аэропорт Luis Munoz Marin International, город San Juan

In [15]:
g.size()

Origin
ABE      4807
ABI      2660
ABQ     41146
ABY      1095
ACK       457
ACT      1993
ACV      3714
ACY       116
ADK       102
ADQ       706
AEX      2330
AGS      2403
AKN       116
ALB     13474
ALO       323
AMA      7496
ANC     19327
ASE      5307
ATL    414513
ATW      5873
AUS     49623
AVL      4399
AVP      2386
AZO      3924
BDL     29449
BET      1035
BFL      4502
BGM       728
BGR      2879
BHM     23679
        ...  
SPS      1834
SRQ      6432
STL     62733
STT      2972
STX       436
SUN      2871
SUX       122
SWF      4249
SYR     12032
TEX       194
TLH      5912
TOL      1478
TPA     78179
TRI      2117
TUL     23459
TUP        10
TUS     26661
TVC      4262
TWF      1813
TXK      1250
TYR      1585
TYS     14004
VLD       938
VPS      6820
WRG       727
WYS       264
XNA     14112
YAK       725
YKM       340
YUM      3871
dtype: int64

In [16]:
h = g.filter(lambda x: len(x) >= 1000)

In [23]:
print(len(data), len(h))

(7009728, 6978440)


In [25]:
z = h[h.DepDelay > 0]

In [30]:
z.Origin.value_counts()

ATL    175017
ORD    159427
DFW    127749
DEN    104414
LAX     87258
IAH     87139
PHX     82915
LAS     76240
EWR     69612
DTW     59837
SFO     58200
MCO     51364
CLT     48936
BWI     46748
SEA     46162
MSP     44958
SLC     44669
MDW     44426
JFK     43904
PHL     42583
LGA     38484
BOS     37570
SAN     37312
DAL     31205
MIA     30263
HOU     30199
CVG     29465
IAD     29417
OAK     29189
TPA     28880
        ...  
TOL       434
OTZ       433
DLH       432
OME       425
HLN       423
TRI       415
SPI       410
GTF       399
SPS       389
SMX       382
GCC       380
ABY       379
DBQ       374
BRO       342
OAJ       340
TYR       329
SJT       322
CLL       318
TWF       316
EKO       311
ERI       298
TXK       272
FLG       249
GFK       243
LCH       225
OXR       224
ELM       213
MOT       175
PIH       166
COD       161
dtype: int64

In [31]:
h.Origin.value_counts()

ATL    414513
ORD    350380
DFW    281281
DEN    241443
LAX    215608
PHX    199408
IAH    185172
LAS    172876
DTW    161989
SFO    140587
SLC    139088
EWR    138506
MCO    130872
MSP    130289
CLT    126045
LGA    119135
JFK    118804
BOS    117915
SEA    109069
BWI    104074
PHL    100499
SAN     93775
CVG     91265
MDW     87619
DCA     86662
MEM     80966
TPA     78179
IAD     76031
FLL     67177
CLE     65795
        ...  
PIH      1659
TYR      1585
EKO      1580
BQN      1519
CSG      1481
TOL      1478
BRO      1464
ERI      1399
DHN      1397
CIC      1392
GFK      1371
CLL      1367
DBQ      1349
ELM      1336
SIT      1332
SJT      1316
OXR      1292
TXK      1250
SPI      1225
COD      1188
OAJ      1184
ABY      1095
OME      1090
OTZ      1086
MOT      1085
CEC      1063
GCC      1046
BET      1035
EYW      1009
LCH      1000
dtype: int64

In [34]:
v = z.Origin.value_counts() / h.Origin.value_counts()

In [35]:
v.argmax()

'DAL'

#### 6. Аэропорт Dallas Love, город Dallas